language: python
python:
- 2.7
cache:
  directories:
  - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - python: 3.5.1
  - python: pypy
before_install:
- pip install -U pip
- pip install --upgrade pip
- pip install opencv-python
addons:
  apt:
    packages:
    - gifsicle
install:
- make setup
script: make test
env:
  matrix:
  - INTEGRATION_TEST=1
  global:
    secure: P3gmJGXPOVdqMDc6iHtBdwoIO7RZ2FNX/Y7AZxHKnf+npgYM3U2+WX/Rjo8bZzP6UMkhHsFOH/MTvUgwBsIx14D1pG80f4/a1iTFcnrj3QTNM5grKMlPmLw0Ft/gdmPhcoFoyAkSIZS1tufs8HaAuXIIRR+cVl+o/6A3Sf2eCzr9bO++tv+FGlF0VId/7PqklDb1IWLekIaA96trBVNbgajl2OyNHsHn3niFKsVDeGvoBoWazk/rvZWXHXrEDTwxDWIu16NNPUp5dara+7RJKGmpDZYorZBA1bzYPWjHeeJQnKl8fluaU2VbuqyzrGCeRBxOK1lr65rtQ1rIrQsXF1EjEeMFJ4RZ/oliINmtN+cFWeVnuqP4MSEcV7jnJjTf2wn51wO+iB5JPRFpUiQ46oAl6jHLnm12AdSLAjld7+Y1nFYELtNx3k0aRDY8erKvN/kOuNKt5yQQOz1D/lY82OqKmaTE6Cy7oFj3NvT7si8620j1G6iVBEb4NvYT0B6dpoyoJxgzkGIFlmsjsgsqht28xjG3Ax5aW8QxyCcdGfZNihQSrdLnpverjdJ9wiUd+WFEo2F11jr1KYzzscrejEhxSqpKYWC2u5i/F7hMoTm6+Nx34P0VRK08p8jTJaVGuYq1is1f2SAhaJY0AialdIM+sHOkqp+UI3hbrDNPCe8=
deploy:
  provider: heroku
  app:
    master: fanhero-image-processer-stg
    staging: fanhero-image-processer-stg
  api_key:
    secure: P+IlHoOe6xzbzOArVP/7lWRmzWIxI791X2z0yjQ1Jt9glnK5upnMZWYTuV8I4ddLk21C/siqVDd4OkqfiZFpIMyhwbrs2D8x94sWWg2J+RhttM5pDFigRf1q2IzYOYm8BlMKiKfn7FCnl9gnkxCfCtKuGj369odXBRsdY0Ab8db4ebr8vgVqAZM/32NdhK/XXjoA2dh101aJznxWHbyYZItz4FqEG3GIS/sZ/JR4dsWxO+bCgAWyjCZSx3LaetoTp/AnQfOusJ0ashcNBJzk7vV1LkOyCixxXm+SbrSW6dvbHB3H7PXEgkYnPa20weLSchRAEdvDOrzLlBBJ5F9L/XuFYYXDxs1eDpOWS7uIdzY85TXUyVUYOl9pKjqukRJcr+5DyGSSXB/vry3DKFvUE9XUKRa/QM9i+giBR+q/NPHIkDpnHV8rQXjidyaKxXsYV0Tl9IHryAlWbu6Y/2xxonIqhnIBQfVkSyNhpOBzbUrhtu4bReTxhGyaSlAOsumot9NsacSQ+XVxyCSazbT97tF/KnL6kMm/QKskFt4pcL2hSLXVNCtF82gI+++x0cGn6m8FfOEoYKA9erOfrX61RMyoyejWCGEvebUa+FK5FqRI0lpwEUxTtV/l0dQlFVxbDT6BGXNXhN9HEMef7Q77uGVXKmPRuzCYjedICJfWb+Q=
