before_script: "sudo aptitude -y -q install libevent-dev"

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

# command to install dependencies
install: pip install -r test_requirements.txt --use-mirrors

# command to run tests
script: make test-trevis

notifications:
  email: false
