language: python
python:
  - 2.7_with_system_site_packages
  - '3.5.1'
  - pypy
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - python: '3.5.1'
    - python: pypy
env:
  - INTEGRATION_TEST=0
  - UNIT_TEST=0
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - python-numpy
    - python-opencv
    - libimage-exiftool-perl
    - libopencv-dev
    - libjpeg-progs
    - libjpeg-dev
    - libpng-dev
    - libx264-dev
    - libass-dev
    - libvpx1
    - libvpx-dev
    - libwebp-dev
    - webp
    - gifsicle
    - python-numpy
    - python-scipy
    - libcairo2-dev
    - gfortran
    - libopenblas-dev
    - liblapack-dev
    - python-pyexiv2
install:
  - pip install -U pip
  - pip install --upgrade pip
  - make setup
  - pip install coveralls
  - pip install cairosvg
before_script:
  - make redis
script:
  make compile_ext ci_test
after_success:
  coveralls
