language: python

python:
  - "2.6"

# command to install dependencies
install: "sudo aptitude -y -q install libevent-dev python-opencv libcv-dev libcvaux-dev libhighgui-dev; pip install -r test_requirements.txt --use-mirrors"

# command to run tests
script: make test-trevis

notifications:
  email: false
